### ISSUE TITLE
Mention the TabT API docs in the readme?

### ISSUE THREAD

**Issue by roelvan** [subhero24/vttl-api#7]
This could be helpful to understand the underlying API quicker?
[source](http://api.frenoy.net/group__TabTAPIfunctions.html)

**Comment by subhero24** [comment]
Added the link in the readme

**Comment by subhero24** [comment]
@roelvan If you are interested in beta testing my app for the table tennis competition, feel free to try it out at http://competitie.bvdsoftware.be

**Comment by roelvan** [comment]
Cool, just tried it out. Is it a personal project or will it be used by the VTTL?
Design is nice and everything feels snappy and fast.
These icons are confusing and I couldn't guess their meaning:
![IMG_9A38610F7037-1](https://user-images.githubusercontent.com/2583837/147918910-961c0f61-c443-4e9c-802f-ba362b997efe.jpeg)
This horizontal scroll does not work so well on touch devices and the navigation is at a weird position:
![IMG_D6158B2B52F1-1](https://user-images.githubusercontent.com/2583837/147918999-491fe528-9654-4de8-b55b-921d206e9eaa.jpeg)
I have had good experiences with [keen-slider](https://keen-slider.io/) on mobile.

Great app, I will use it on mobile instead of the vttl website.

**Comment by subhero24** [comment]
I fixed the navigation bullets not rendering as they should in safari.
The icons are for different player categories: "men", "women", "youth" and "veterans". I'll think about a way to make it more clear.

It is just a personal project, born out of frustration to lookup the address of the match i had to play on the official vttl website. You could use the "Add to Home Screen" in the share menu if you want a more app-like experience.

Thanks for the feedback.
